name: twentyfive
channels:
  - defaults
dependencies:
  - python>=3.12
  - pip>=22.2
  - pip:
    - build>=0.8.0
    - pytest>=8.0
    - ruff>=0.4
    - mypy>=1.10
#prefix: /home/<user>/anaconda3/envs/twentyfive
